DATA ELECTION; INPUT annee gagnant :$12. perdant :$12.; lines;
1952 EISENHOWER STEVENSON
1956 EISENHOWER STEVENSON
1960 KENNEDY    NIXON
1964 JOHNSON    GOLDWATER
1968 NIXON      HUMPHREY
1972 NIXON      MCGOVERN
1976 CARTER     FORD
PROC PRINT;
DATA CANDIDAT; INPUT nom :$12. parti $ etat $; lines;
EISENHOWER R TEXAS
STEVENSON  D ILL
NIXON      R CALIF
GOLDWATER  R ARIZ
KENNEDY    D MASS
JOHNSON    D TEXAS
HUMPHREY   D MINN
MCGOVERN   D S.DAK
FORD       R MICH
CARTER     D GA
;
PROC PRINT;
RUN;
